name: CI

on: 
  push:
    branches:
        - main
  pull_request:
     branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - run: echo "Deploying to staging"
