name: ci

 on:
    push:
     branches:
       - main
   pull_request:
       - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: echo "running build..."
